### ISSUE TITLE
`block (2 levels) in <module:Client>': Plase set up your applications and default_app (Sendbird::Client::ApiKeyMissingError)

### ISSUE THREAD

**Issue by jtongtech** [GustavoCaso/sendbird#11]
require 'sendbird'

load './local_env.rb' if File.exist?('./local_env.rb')

Sendbird.applications = {my_awesome_app: ENV['API_KEY']}
Sendbird.user = ENV['username']
Sendbird.password = ENV['password']
Sendbird.default_app = ENV['app_name']

user = Sendbird::User.new('testing_user_interface_1')
user.nickname('Yolo').profile_url('udbue').timezone('Europe/London').request!

I keep getting the error 
`block (2 levels) in <module:Client>': Plase set up your applications and default_app (Sendbird::Client::ApiKeyMissingError)

ENV['API_KEY'] = 'api-key-is-from-sendbird'
ENV['API_TOKEN'] = 'token-is-also-from-sendbird'
ENV['app_name'] = 'my_awesome_app'
ENV['username'] = 'myemail@gmail.com'
ENV['password'] = 'password-is-also-correct'

**Comment by jkeam** [comment]
You are close but a bit off.  Your key is a symbol where in your env specifies a string.  Try this:

```ruby
Sendbird.applications = {my_awesome_app: ENV['API_KEY']}
Sendbird.user = 'fake@gmail.com'
Sendbird.password = 'secret_pass'
Sendbird.default_app = :my_awesome_app
```

**Comment by GustavoCaso** [comment]
I will close this one. Thanks @jkeam for the support.
