### ISSUE TITLE
Missing Delete User

### ISSUE THREAD

**Issue by jkeam** [GustavoCaso/sendbird#6]
Looking over the Sendbird docs and notice that this library is missing deleting a user.

https://docs.sendbird.com/platform#user

Delete a user | DELETE /users/{user_id} | Deletes the user.

**Comment by GustavoCaso** [comment]
Hey @jkeam thanks for reporting. I'm looking forward to spending some time with the lib. As we talk in your PR I want to remove all the interface logic.

If in the meantime you want to open a PR I would gladly appreciate it.

**Comment by jkeam** [comment]
I added it into one of my branches but alas have not yet written any tests for it yet.

**Branch**
https://github.com/jkeam/sendbird/tree/delete_user

**Actual Commit**
https://github.com/jkeam/sendbird/commit/13b687a86660bf723a235123771d4abaa7daba34

**Comment by GustavoCaso** [comment]
Thanks @jkeam if you add some test we can merge it. Also this weekend I hope to have some free time to dedicate to the library

**Comment by jkeam** [comment]
Took me a while to get around to it, but finally added some tests.  Here is the PR:

https://github.com/GustavoCaso/sendbird/pull/7

**Comment by GustavoCaso** [comment]
Thank you so much

**Comment by GustavoCaso** [comment]
Fixed in #7

**Comment by jkeam** [comment]
Thank you for merging this on!  Thoughts on when you would cut a release?  I'd love to able to have


`gem 'sendbird'`


instead of


`gem 'sendbird', github: 'GustavoCaso/sendbird', branch: 'develop'`


in my Gemfile.

**Comment by GustavoCaso** [comment]
@jkeam I released the gem. Sorry for the delay
